version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: fastapi-cicd-repo
    IMAGE_TAG: latest
    ECR_HOST: host.docker.internal:5100
    LOCALSTACK_ENDPOINT: http://host.docker.internal:4566

phases:
  pre_build:
    commands:
      - echo "Starting build..."
      - pwd
      - ls -la   # DEBUG (very important)

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $IMAGE_REPO_NAME .

      - echo "Tagging image..."
      - docker tag $IMAGE_REPO_NAME:latest $ECR_HOST/$IMAGE_REPO_NAME:latest

  post_build:
    commands:
      - echo "Pushing to ECR..."
      - docker push $ECR_HOST/$IMAGE_REPO_NAME:latest

      - echo "Deploying to ECS..."
      - aws ecs update-service \
          --cluster fastapi-cicd-cluster \
          --service fastapi-service \
          --force-new-deployment \
          --endpoint-url $LOCALSTACK_ENDPOINT